### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by TheChymera** [Jimmy2027/MLEBE#2]
I don't think the [blacklist document](https://github.com/Jimmy2027/MLEBE/tree/master/mlebe/Blacklist) is relevant to the software in a general-purpose context. It looks specific to the execution for the article. Consequently it should be moved to `mlebeRepSeP/data` and tracked and used from there.

**Comment by TheChymera** [comment]
When you close an issue, could you please add a link to the commit which addresses it? easier to keep track of things that way.

**Comment by Jimmy2027** [comment]
right, the issue was addressed [here](https://github.com/Jimmy2027/MLEBE/commit/2764044d71299a947e1a14e6502e70c98e03a5cc)
